kr.lul.urs:
  dao:
    saveAndFlush: false
  logging.pattern: "%-4relative [%thread] %-5level %logger{60} - %msg %n"
  resource.file.storage.dir: # some directory
spring:
  datasource:
    url: jdbc:mysql://localhost/urs
    username: database_instance_username # Overwrite by `[PROJECT]/config/application.yml`. See `[PROJECT]/config/sample-application.yml`.
    password: database_instance_password # Overwrite by `[PROJECT]/config/application.yml`. See `[PROJECT]/config/sample-application.yml`.
    driver-class-name: 'com.mysql.jdbc.Driver'
    sql-script-encoding: UTF-8
    connection-test-query: 'SELECT 1'
    validation-query: 'SELECT 1'
  jpa:
    database: mysql
    show-sql: false
    generate-ddl: false
    open-in-view: false
    properties:
      javax.persistence.sharedCache.mode: ALL
      hibernate.cache:
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
logging:
  level:
    sun: fatal
    java: fatal
    javax: fatal
    org.apache: warn
    org.springframework: warn
    org.hibernate: warn
    org.thymeleaf: warn