kr.lul.urs:
  resource.file.storage.dir: ~/resourceFileStorage
  logging.pattern: "%d{HH:mm:ss.SSS} %-4relative [%thread] %-5level %logger{35} - %msg %n"
spring:
  datasource:
    username: 'root'
    password: ''
  jpa:
    generate-ddl: true
    properties:
      hibernate.generateStatistics: true
  thymeleaf:
    cache: false
  messages:
    cache-seconds: 1
server:
  port: 8080
logging:
  level:
    org.hibernate: warn
    org.hibernate.SQL: debug
    kr.lul: debug
