spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
server:
  address: 127.0.0.1 # Change to test microservice architecture.
  port: 80 # Change for dev & test to pass OS security policy.
logging:
  level:
    sun: fatal
    java: fatal
    javax: fatal
    org.apache: warn
    org.springframework: warn
    org.hibernate: warn
    org.thymeleaf: warn